### ISSUE TITLE
Container not starting

### ISSUE THREAD

**Issue by exylian** [elmerfdz/docker-bind#12]
Hello there, 

tryed to use this docker build. Container is not able to start.
Used with the following command:

> docker run --name dns -d -it --restart=always -p 53:53/tcp -p 53:53/udp -p 10000:10000/tcp -v /srv/docker/bind:/data eafxx/bind

> ---------------------,
> |  Starting named   |,
> ---------------------,
> ,
> 01-Aug-2020 18:36:57.266 starting BIND 9.11.5-P4-5.1ubuntu2.2-Ubuntu (Extended Support Version) <id:998753c>,
> 01-Aug-2020 18:36:57.266 running on Linux aarch64 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020,
> 01-Aug-2020 18:36:57.266 built with '--build=aarch64-linux-gnu' '--prefix=/usr' '--includedir=/usr/include' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/lib/aarch64-linux-gnu' '--libexecdir=/usr/lib/aarch64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--libdir=/usr/lib/aarch64-linux-gnu' '--sysconfdir=/etc/bind' '--with-python=python3' '--localstatedir=/' '--enable-threads' '--enable-largefile' '--with-libtool' '--enable-shared' '--enable-static' '--with-gost=no' '--with-openssl=/usr' '--with-gssapi=/usr' '--with-libidn2' '--with-libjson=/usr' '--without-lmdb' '--with-gnu-ld' '--with-geoip=/usr' '--with-atf=no' '--enable-ipv6' '--enable-rrl' '--enable-filter-aaaa' '--enable-native-pkcs11' '--with-pkcs11=/usr/lib/softhsm/libsofthsm2.so' '--with-randomdev=/dev/urandom' 'build_alias=aarch64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/bind9-ShBWM0/bind9-9.11.5.P4+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -fno-strict-aliasing -fno-delete-null-pointer-checks -DNO_VERSION_DATE -DDIG_SIGCHASE' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2',
> 01-Aug-2020 18:36:57.266 running as: named -u bind -g -c /etc/bind/named.conf,
> 01-Aug-2020 18:36:57.266 compiled by GCC 9.2.1 20191008,
> 01-Aug-2020 18:36:57.266 compiled with OpenSSL version: OpenSSL 1.1.1c  28 May 2019,
> 01-Aug-2020 18:36:57.266 linked to OpenSSL version: OpenSSL 1.1.1c  28 May 2019,
> 01-Aug-2020 18:36:57.267 compiled with libxml2 version: 2.9.4,
> 01-Aug-2020 18:36:57.267 linked to libxml2 version: 20904,
> 01-Aug-2020 18:36:57.267 compiled with libjson-c version: 0.13.1,
> 01-Aug-2020 18:36:57.267 linked to libjson-c version: 0.13.1,
> 01-Aug-2020 18:36:57.267 threads support is enabled,
> 01-Aug-2020 18:36:57.267 ----------------------------------------------------,
> 01-Aug-2020 18:36:57.267 BIND 9 is maintained by Internet Systems Consortium,,
> 01-Aug-2020 18:36:57.267 Inc. (ISC), a non-profit 501(c)(3) public-benefit ,
> 01-Aug-2020 18:36:57.267 corporation.  Support and training for BIND 9 are ,
> 01-Aug-2020 18:36:57.267 available at https://www.isc.org/support,
> 01-Aug-2020 18:36:57.267 ----------------------------------------------------,
> 01-Aug-2020 18:36:57.267 found 4 CPUs, using 4 worker threads,
> 01-Aug-2020 18:36:57.267 using 3 UDP listeners per interface,
> 01-Aug-2020 18:36:57.268 using up to 4096 sockets,
> 01-Aug-2020 18:36:57.276 loading configuration from '/etc/bind/named.conf',
> 01-Aug-2020 18:36:57.276 open: /etc/bind/named.conf: file not found,
> 01-Aug-2020 18:36:57.277 loading configuration: file not found,
> 01-Aug-2020 18:36:57.277 exiting (due to fatal error),

**Comment by elforesto** [comment]
I'm running into this same issue using the image as-is. Is there some undocumented required setup?

**Comment by v00g100skr** [comment]
+1
